name: FlowFi Live Scanner

on:
  workflow_dispatch:

jobs:
  scanner:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Debug Repository
        run: |
          pwd
          echo "========================"
          ls
          echo "========================"
          ls app
          echo "========================"
          ls app/market_data
          echo "========================"
          cat app/market_data/__init__.py

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Scanner
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: |
          python main.py
